export const ACTION_CHANGE_FIRST_NAME = 'ACTION_CHANGE_FIRST_NAME';
export const ACTION_CHANGE_SECOND_NAME = 'ACTION_CHANGE_SECOND_NAME';
export const ACTION_CHANGE_LANG = 'ACTION_CHANGE_LANG';

export const ACTION_CHANGE_LOGIN = 'ACTION_CHANGE_LOGIN';
export const ACTION_CHANGE_PASSWORD = 'ACTION_CHANGE_PASSWORD';

// action types
export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const API_REQUEST_SETTINGS = "API_REQUEST_SETTINGS";
export const API_SUCCESS_SETTINGS = "API_SUCCESS_SETTINGS";

export const API_REQUEST_CATEGORIES = "API_REQUEST_CATEGORIES";
export const API_SUCCESS_CATEGORIES = "API_SUCCESS_CATEGORIES";

export const API_REQUEST_LOGIN = "API_REQUEST_LOGIN";
export const API_SUCCESS_LOGIN = "API_SUCCESS_LOGIN";

export const API_REQUEST_ABOUT = "API_REQUEST_ABOUT";
export const API_SUCCESS_ABOUT = "API_SUCCESS_ABOUT";

export const API_REQUEST_PRODUCT_ITEM = "API_REQUEST_PRODUCT_ITEM";
export const API_SUCCESS_PRODUCT_ITEM = "API_SUCCESS_PRODUCT_ITEM";

export const API_REQUEST_PRODUCT_ITEMS = "API_REQUEST_PRODUCT_ITEMS";
export const API_SUCCESS_PRODUCT_ITEMS = "API_SUCCESS_PRODUCT_ITEMS";

export const API_REQUEST_NEWS_ITEM = "API_REQUEST_NEWS_ITEM";
export const API_SUCCESS_NEWS_ITEM = "API_SUCCESS_NEWS_ITEM";

export const API_REQUEST_NEWS_ITEMS = "API_REQUEST_NEWS_ITEMS";
export const API_SUCCESS_NEWS_ITEMS = "API_SUCCESS_NEWS_ITEMS";


